interface Coin {
  count: number;
  timestamp: string;
  symbols: {
    binance_symbol: string[];
    wallex_symbol: [string, string][];
  };
}

const binance_wallex_common_symbols: Coin = {
  "count": 203,
  "timestamp": "2025-11-29T15:29:44.730Z",
  "symbols": {
    "binance_symbol": [
      "BTCUSDT",
      "ETHUSDT",
      "BNBUSDT",
      "LTCUSDT",
      "ADAUSDT",
      "XRPUSDT",
      "XLMUSDT",
      "TRXUSDT",
      "ETCUSDT",
      "USDCUSDT",
      "LINKUSDT",
      "WAVESUSDT",
      "HOTUSDT",
      "ZILUSDT",
      "ZRXUSDT",
      "FETUSDT",
      "BATUSDT",
      "XMRUSDT",
      "ZECUSDT",
      "CELRUSDT",
      "DASHUSDT",
      "OMGUSDT",
      "ENJUSDT",
      "ATOMUSDT",
      "ONEUSDT",
      "ALGOUSDT",
      "DOGEUSDT",
      "ANKRUSDT",
      "WINUSDT",
      "MTLUSDT",
      "CVCUSDT",
      "CHZUSDT",
      "BANDUSDT",
      "XTZUSDT",
      "RENUSDT",
      "HBARUSDT",
      "NKNUSDT",
      "RLCUSDT",
      "BCHUSDT",
      "SOLUSDT",
      "CTSIUSDT",
      "CHRUSDT",
      "MDTUSDT",
      "KNCUSDT",
      "LRCUSDT",
      "COMPUSDT",
      "SNXUSDT",
      "MKRUSDT",
      "DAIUSDT",
      "STORJUSDT",
      "MANAUSDT",
      "YFIUSDT",
      "BALUSDT",
      "JSTUSDT",
      "CRVUSDT",
      "SANDUSDT",
      "NMRUSDT",
      "DOTUSDT",
      "RSRUSDT",
      "PAXGUSDT",
      "TRBUSDT",
      "SUSHIUSDT",
      "EGLDUSDT",
      "RUNEUSDT",
      "UMAUSDT",
      "UNIUSDT",
      "OXTUSDT",
      "AVAXUSDT",
      "AAVEUSDT",
      "NEARUSDT",
      "FILUSDT",
      "INJUSDT",
      "AUDIOUSDT",
      "AXSUSDT",
      "SKLUSDT",
      "GRTUSDT",
      "1INCHUSDT",
      "TWTUSDT",
      "SFPUSDT",
      "CAKEUSDT",
      "OMUSDT",
      "ALICEUSDT",
      "SUPERUSDT",
      "PUNDIXUSDT",
      "SLPUSDT",
      "SHIBUSDT",
      "ICPUSDT",
      "POLSUSDT",
      "MASKUSDT",
      "LPTUSDT",
      "DEXEUSDT",
      "C98USDT",
      "QNTUSDT",
      "FLOWUSDT",
      "RAYUSDT",
      "REQUSDT",
      "GNOUSDT",
      "ELFUSDT",
      "DYDXUSDT",
      "GALAUSDT",
      "ILVUSDT",
      "YGGUSDT",
      "AGLDUSDT",
      "ENSUSDT",
      "JASMYUSDT",
      "AMPUSDT",
      "PYRUSDT",
      "BICOUSDT",
      "FXSUSDT",
      "CVXUSDT",
      "PEOPLEUSDT",
      "IMXUSDT",
      "API3USDT",
      "BTTCUSDT",
      "WOOUSDT",
      "TUSDT",
      "GMTUSDT",
      "APEUSDT",
      "BSWUSDT",
      "NEXOUSDT",
      "OPUSDT",
      "GMXUSDT",
      "APTUSDT",
      "OSMOUSDT",
      "MAGICUSDT",
      "HIFIUSDT",
      "RPLUSDT",
      "SSVUSDT",
      "GLMUSDT",
      "ARBUSDT",
      "RDNTUSDT",
      "WBTCUSDT",
      "EDUUSDT",
      "SUIUSDT",
      "PEPEUSDT",
      "FLOKIUSDT",
      "PENDLEUSDT",
      "ARKMUSDT",
      "WLDUSDT",
      "SEIUSDT",
      "CYBERUSDT",
      "TIAUSDT",
      "MEMEUSDT",
      "BLURUSDT",
      "JTOUSDT",
      "BONKUSDT",
      "JUPUSDT",
      "PYTHUSDT",
      "PIXELUSDT",
      "STRKUSDT",
      "WIFUSDT",
      "METISUSDT",
      "AEVOUSDT",
      "BOMEUSDT",
      "ETHFIUSDT",
      "ENAUSDT",
      "WUSDT",
      "TNSRUSDT",
      "TAOUSDT",
      "NOTUSDT",
      "IOUSDT",
      "ZROUSDT",
      "GUSDT",
      "BANANAUSDT",
      "RENDERUSDT",
      "TONUSDT",
      "DOGSUSDT",
      "POLUSDT",
      "NEIROUSDT",
      "TURBOUSDT",
      "CATIUSDT",
      "HMSTRUSDT",
      "EIGENUSDT",
      "KAIAUSDT",
      "PNUTUSDT",
      "ORCAUSDT",
      "MOVEUSDT",
      "MEUSDT",
      "PENGUUSDT",
      "BIOUSDT",
      "AIXBTUSDT",
      "CGPTUSDT",
      "COOKIEUSDT",
      "SUSDT",
      "LAYERUSDT",
      "KAITOUSDT",
      "FORMUSDT",
      "ONDOUSDT",
      "VIRTUALUSDT",
      "SYRUPUSDT",
      "KMNOUSDT",
      "AUSDT",
      "SAHARAUSDT",
      "PROVEUSDT",
      "LINEAUSDT",
      "PUMPUSDT",
      "SKYUSDT",
      "XPLUSDT",
      "2ZUSDT",
      "MORPHOUSDT",
      "ASTERUSDT",
      "GIGGLEUSDT",
      "BANKUSDT"
    ],
    "wallex_symbol": [
      [
        "BTCTMN",
        "BTCUSDT"
      ],
      [
        "ETHTMN",
        "ETHUSDT"
      ],
      [
        "BNBTMN",
        "BNBUSDT"
      ],
      [
        "LTCTMN",
        "LTCUSDT"
      ],
      [
        "ADATMN",
        "ADAUSDT"
      ],
      [
        "XRPTMN",
        "XRPUSDT"
      ],
      [
        "XLMTMN",
        "XLMUSDT"
      ],
      [
        "TRXTMN",
        "TRXUSDT"
      ],
      [
        "ETCTMN",
        "ETCUSDT"
      ],
      [
        "USDCTMN",
        "USDCUSDT"
      ],
      [
        "LINKTMN",
        "LINKUSDT"
      ],
      [
        "WAVESTMN",
        "WAVESUSDT"
      ],
      [
        "HOTTMN",
        "HOTUSDT"
      ],
      [
        "ZILTMN",
        "ZILUSDT"
      ],
      [
        "ZRXTMN",
        "ZRXUSDT"
      ],
      [
        "FETTMN",
        "FETUSDT"
      ],
      [
        "BATTMN",
        "BATUSDT"
      ],
      [
        "XMRTMN",
        "XMRUSDT"
      ],
      [
        "ZECTMN",
        "ZECUSDT"
      ],
      [
        "CELRTMN",
        "CELRUSDT"
      ],
      [
        "DASHTMN",
        "DASHUSDT"
      ],
      [
        "OMGTMN",
        "OMGUSDT"
      ],
      [
        "ENJTMN",
        "ENJUSDT"
      ],
      [
        "ATOMTMN",
        "ATOMUSDT"
      ],
      [
        "ONETMN",
        "ONEUSDT"
      ],
      [
        "ALGOTMN",
        "ALGOUSDT"
      ],
      [
        "DOGETMN",
        "DOGEUSDT"
      ],
      [
        "ANKRTMN",
        "ANKRUSDT"
      ],
      [
        "WINTMN",
        "WINUSDT"
      ],
      [
        "MTLTMN",
        "MTLUSDT"
      ],
      [
        "CVCTMN",
        "CVCUSDT"
      ],
      [
        "CHZTMN",
        "CHZUSDT"
      ],
      [
        "BANDTMN",
        "BANDUSDT"
      ],
      [
        "XTZTMN",
        "XTZUSDT"
      ],
      [
        "RENTMN",
        "RENUSDT"
      ],
      [
        "HBARTMN",
        "HBARUSDT"
      ],
      [
        "NKNTMN",
        "NKNUSDT"
      ],
      [
        "RLCTMN",
        "RLCUSDT"
      ],
      [
        "BCHTMN",
        "BCHUSDT"
      ],
      [
        "SOLTMN",
        "SOLUSDT"
      ],
      [
        "CTSITMN",
        "CTSIUSDT"
      ],
      [
        "CHRTMN",
        "CHRUSDT"
      ],
      [
        "MDTTMN",
        "MDTUSDT"
      ],
      [
        "KNCTMN",
        "KNCUSDT"
      ],
      [
        "LRCTMN",
        "LRCUSDT"
      ],
      [
        "COMPTMN",
        "COMPUSDT"
      ],
      [
        "SNXTMN",
        "SNXUSDT"
      ],
      [
        "MKRTMN",
        "MKRUSDT"
      ],
      [
        "DAITMN",
        "DAIUSDT"
      ],
      [
        "STORJTMN",
        "STORJUSDT"
      ],
      [
        "MANATMN",
        "MANAUSDT"
      ],
      [
        "YFITMN",
        "YFIUSDT"
      ],
      [
        "BALTMN",
        "BALUSDT"
      ],
      [
        "JSTTMN",
        "JSTUSDT"
      ],
      [
        "CRVTMN",
        "CRVUSDT"
      ],
      [
        "SANDTMN",
        "SANDUSDT"
      ],
      [
        "NMRTMN",
        "NMRUSDT"
      ],
      [
        "DOTTMN",
        "DOTUSDT"
      ],
      [
        "RSRTMN",
        "RSRUSDT"
      ],
      [
        "PAXGTMN",
        "PAXGUSDT"
      ],
      [
        "TRBTMN",
        "TRBUSDT"
      ],
      [
        "SUSHITMN",
        "SUSHIUSDT"
      ],
      [
        "EGLDTMN",
        "EGLDUSDT"
      ],
      [
        "RUNETMN",
        "RUNEUSDT"
      ],
      [
        "UMATMN",
        "UMAUSDT"
      ],
      [
        "UNITMN",
        "UNIUSDT"
      ],
      [
        "OXTTMN",
        "OXTUSDT"
      ],
      [
        "AVAXTMN",
        "AVAXUSDT"
      ],
      [
        "AAVETMN",
        "AAVEUSDT"
      ],
      [
        "NEARTMN",
        "NEARUSDT"
      ],
      [
        "FILTMN",
        "FILUSDT"
      ],
      [
        "INJTMN",
        "INJUSDT"
      ],
      [
        "AUDIOTMN",
        "AUDIOUSDT"
      ],
      [
        "AXSTMN",
        "AXSUSDT"
      ],
      [
        "SKLTMN",
        "SKLUSDT"
      ],
      [
        "GRTTMN",
        "GRTUSDT"
      ],
      [
        "1INCHTMN",
        "1INCHUSDT"
      ],
      [
        "TWTTMN",
        "TWTUSDT"
      ],
      [
        "SFPTMN",
        "SFPUSDT"
      ],
      [
        "CAKETMN",
        "CAKEUSDT"
      ],
      [
        "OMTMN",
        "OMUSDT"
      ],
      [
        "ALICETMN",
        "ALICEUSDT"
      ],
      [
        "SUPERTMN",
        "SUPERUSDT"
      ],
      [
        "PUNDIXTMN",
        "PUNDIXUSDT"
      ],
      [
        "SLPTMN",
        "SLPUSDT"
      ],
      [
        "SHIBTMN",
        "SHIBUSDT"
      ],
      [
        "ICPTMN",
        "ICPUSDT"
      ],
      [
        "POLSTMN",
        "POLSUSDT"
      ],
      [
        "MASKTMN",
        "MASKUSDT"
      ],
      [
        "LPTTMN",
        "LPTUSDT"
      ],
      [
        "DEXETMN",
        "DEXEUSDT"
      ],
      [
        "C98TMN",
        "C98USDT"
      ],
      [
        "QNTTMN",
        "QNTUSDT"
      ],
      [
        "FLOWTMN",
        "FLOWUSDT"
      ],
      [
        "RAYTMN",
        "RAYUSDT"
      ],
      [
        "REQTMN",
        "REQUSDT"
      ],
      [
        "GNOTMN",
        "GNOUSDT"
      ],
      [
        "ELFTMN",
        "ELFUSDT"
      ],
      [
        "DYDXTMN",
        "DYDXUSDT"
      ],
      [
        "GALATMN",
        "GALAUSDT"
      ],
      [
        "ILVTMN",
        "ILVUSDT"
      ],
      [
        "YGGTMN",
        "YGGUSDT"
      ],
      [
        "AGLDTMN",
        "AGLDUSDT"
      ],
      [
        "ENSTMN",
        "ENSUSDT"
      ],
      [
        "JASMYTMN",
        "JASMYUSDT"
      ],
      [
        "AMPTMN",
        "AMPUSDT"
      ],
      [
        "PYRTMN",
        "PYRUSDT"
      ],
      [
        "BICOTMN",
        "BICOUSDT"
      ],
      [
        "FXSTMN",
        "FXSUSDT"
      ],
      [
        "CVXTMN",
        "CVXUSDT"
      ],
      [
        "PEOPLETMN",
        "PEOPLEUSDT"
      ],
      [
        "IMXTMN",
        "IMXUSDT"
      ],
      [
        "API3TMN",
        "API3USDT"
      ],
      [
        "BTTCTMN",
        "BTTCUSDT"
      ],
      [
        "WOOTMN",
        "WOOUSDT"
      ],
      [
        "TTMN",
        "TUSDT"
      ],
      [
        "GMTTMN",
        "GMTUSDT"
      ],
      [
        "APETMN",
        "APEUSDT"
      ],
      [
        "BSWTMN",
        "BSWUSDT"
      ],
      [
        "NEXOTMN",
        "NEXOUSDT"
      ],
      [
        "OPTMN",
        "OPUSDT"
      ],
      [
        "GMXTMN",
        "GMXUSDT"
      ],
      [
        "APTTMN",
        "APTUSDT"
      ],
      [
        "OSMOTMN",
        "OSMOUSDT"
      ],
      [
        "MAGICTMN",
        "MAGICUSDT"
      ],
      [
        "HIFITMN",
        "HIFIUSDT"
      ],
      [
        "RPLTMN",
        "RPLUSDT"
      ],
      [
        "SSVTMN",
        "SSVUSDT"
      ],
      [
        "GLMTMN",
        "GLMUSDT"
      ],
      [
        "ARBTMN",
        "ARBUSDT"
      ],
      [
        "RDNTTMN",
        "RDNTUSDT"
      ],
      [
        "WBTCTMN",
        "WBTCUSDT"
      ],
      [
        "EDUTMN",
        "EDUUSDT"
      ],
      [
        "SUITMN",
        "SUIUSDT"
      ],
      [
        "PEPETMN",
        "PEPEUSDT"
      ],
      [
        "FLOKITMN",
        "FLOKIUSDT"
      ],
      [
        "PENDLETMN",
        "PENDLEUSDT"
      ],
      [
        "ARKMTMN",
        "ARKMUSDT"
      ],
      [
        "WLDTMN",
        "WLDUSDT"
      ],
      [
        "SEITMN",
        "SEIUSDT"
      ],
      [
        "CYBERTMN",
        "CYBERUSDT"
      ],
      [
        "TIATMN",
        "TIAUSDT"
      ],
      [
        "MEMETMN",
        "MEMEUSDT"
      ],
      [
        "BLURTMN",
        "BLURUSDT"
      ],
      [
        "JTOTMN",
        "JTOUSDT"
      ],
      [
        "BONKTMN",
        "BONKUSDT"
      ],
      [
        "JUPTMN",
        "JUPUSDT"
      ],
      [
        "PYTHTMN",
        "PYTHUSDT"
      ],
      [
        "PIXELTMN",
        "PIXELUSDT"
      ],
      [
        "STRKTMN",
        "STRKUSDT"
      ],
      [
        "WIFTMN",
        "WIFUSDT"
      ],
      [
        "METISTMN",
        "METISUSDT"
      ],
      [
        "AEVOTMN",
        "AEVOUSDT"
      ],
      [
        "BOMETMN",
        "BOMEUSDT"
      ],
      [
        "ETHFITMN",
        "ETHFIUSDT"
      ],
      [
        "ENATMN",
        "ENAUSDT"
      ],
      [
        "WTMN",
        "WUSDT"
      ],
      [
        "TNSRTMN",
        "TNSRUSDT"
      ],
      [
        "TAOTMN",
        "TAOUSDT"
      ],
      [
        "NOTTMN",
        "NOTUSDT"
      ],
      [
        "IOTMN",
        "IOUSDT"
      ],
      [
        "ZROTMN",
        "ZROUSDT"
      ],
      [
        "GTMN",
        "GUSDT"
      ],
      [
        "BANANATMN",
        "BANANAUSDT"
      ],
      [
        "RENDERTMN",
        "RENDERUSDT"
      ],
      [
        "TONTMN",
        "TONUSDT"
      ],
      [
        "DOGSTMN",
        "DOGSUSDT"
      ],
      [
        "POLTMN",
        "POLUSDT"
      ],
      [
        "NEIROTMN",
        "NEIROUSDT"
      ],
      [
        "TURBOTMN",
        "TURBOUSDT"
      ],
      [
        "CATITMN",
        "CATIUSDT"
      ],
      [
        "HMSTRTMN",
        "HMSTRUSDT"
      ],
      [
        "EIGENTMN",
        "EIGENUSDT"
      ],
      [
        "KAIATMN",
        "KAIAUSDT"
      ],
      [
        "PNUTTMN",
        "PNUTUSDT"
      ],
      [
        "ORCATMN",
        "ORCAUSDT"
      ],
      [
        "MOVETMN",
        "MOVEUSDT"
      ],
      [
        "METMN",
        "MEUSDT"
      ],
      [
        "PENGUTMN",
        "PENGUUSDT"
      ],
      [
        "BIOTMN",
        "BIOUSDT"
      ],
      [
        "AIXBTTMN",
        "AIXBTUSDT"
      ],
      [
        "CGPTTMN",
        "CGPTUSDT"
      ],
      [
        "COOKIETMN",
        "COOKIEUSDT"
      ],
      [
        "STMN",
        "SUSDT"
      ],
      [
        "LAYERTMN",
        "LAYERUSDT"
      ],
      [
        "KAITOTMN",
        "KAITOUSDT"
      ],
      [
        "FORMTMN",
        "FORMUSDT"
      ],
      [
        "ONDOTMN",
        "ONDOUSDT"
      ],
      [
        "VIRTUALTMN",
        "VIRTUALUSDT"
      ],
      [
        "SYRUPTMN",
        "SYRUPUSDT"
      ],
      [
        "KMNOTMN",
        "KMNOUSDT"
      ],
      [
        "ATMN",
        "AUSDT"
      ],
      [
        "SAHARATMN",
        "SAHARAUSDT"
      ],
      [
        "PROVETMN",
        "PROVEUSDT"
      ],
      [
        "LINEATMN",
        "LINEAUSDT"
      ],
      [
        "PUMPTMN",
        "PUMPUSDT"
      ],
      [
        "SKYTMN",
        "SKYUSDT"
      ],
      [
        "XPLTMN",
        "XPLUSDT"
      ],
      [
        "2ZTMN",
        "2ZUSDT"
      ],
      [
        "MORPHOTMN",
        "MORPHOUSDT"
      ],
      [
        "ASTERTMN",
        "ASTERUSDT"
      ],
      [
        "GIGGLETMN",
        "GIGGLEUSDT"
      ],
      [
        "BANKTMN",
        "BANKUSDT"
      ]
    ]
  }
}

export default binance_wallex_common_symbols;